name: Run Robot Tests on Self-Hosted

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python dependencies
        run: pip install -r requirements.txt

      - name: Create results directory
        run: mkdir -p results

      - name: Run Robot Framework tests
        run: robot -d ./results tests

      - name: Upload Robot Framework reports as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: robotframework-results
          path: results/